config/routes.rb

Rails.application.routes.draw do
  
  
  get 'speak/watson'
  get 'speak/star_wars'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
  get '/form', to: 'pages#form'
  get '/residential', to: 'pages#residential'
  get '/commercial', to: 'pages#commercial'
  get '/google', to: 'google#index'
  get '/quote_confirm', to: 'pages#quote_confirm'
  get '/terms_and_conditions', to: 'pages#terms_and_conditions'
  get 'interventions/new'  
  get 'get_buildings_by_customer/:customer_id', to: 'intervention#get_buildings_by_customer'  
  get '/buildings_search' => 'intervention#building_search'
  get 'get_battery_by_buildings/:buildings_id', to: 'intervention#get_battery_by_buildings'  
  get '/battery_search' => 'intervention#battery_search'
  get '/get_column_by_battery/:battery_id', to: 'intervention#get_column_by_battery'  
  get '/column_search' => 'intervention#column_search'
  get '/get_elevator_by_column/:column_id', to: 'intervention#get_elevator_by_column'  
  get '/elevator_search' => 'intervention#elevator_search'
  #get '/leads', to: 'leads#create'
 

  get 'home/index'
  
  resources :quotes
  resources :employees
  resources :leads
  resources :interventions

  # get '/WatsonSpeaker/watson'

  # Rails.application.routes.draw do
  # get 'speak/watson'
  #   devise_for :users, controllers: {
  #     sessions: 'users/sessions'
  #   }
  # end

end

app/models/intervention.rb
class Intervention < ApplicationRecord
    belongs_to :customer
    belongs_to :building
    belongs_to :battery, optional: true
    belongs_to :column, optional: true
    belongs_to :elevator, optional: true
    belongs_to :employee


    def company_name
        
    end

   

end

app/controllers/intervention_controller.rb
class InterventionController < ApplicationController
  skip_before_action :verify_authenticity_token
    before_action :set_interventions, only: [:show, :edit, :update, :destroy]
   
    def new
      @intervention = Intervention.new
    end

    def get_elevator_by_column
      puts params[:column_id]
        @elevator = Elevator.where("column_id = ?", params[:column_id])
        puts @elevator
        respond_to do |format|
          format.json { render :json => @elevator }
        end
      end 
      def elevator_search
        if params[:location].present? && params[:column].strip != ""
          @elevator = Elevator.where("column_id = ?", params[:column])
        else
          @elevator = Elevator.all
        end
      end
    def get_column_by_battery
      @column = Column.where("battery_id = ?", params[:battery_id])
      puts @column
      respond_to do |format|
        format.json { render :json => @column }
      end
    end 
    def column_search
      if params[:location].present? && params[:battery_id].strip != ""
        @column = Column.where("battery_id = ?", params[:battery_id])
      else
        @column = Column.all
      end
    end

    def get_battery_by_buildings
      @battery = Battery.where(building_id: params[:buildings_id])
      puts @battery
      respond_to do |format|
        format.json { render :json => @battery }
      end
    end 
    def battery_search
      if params[:location].present? && params[:buildings].strip != ""
        @battery = Battery.where("buildings_id = ?", params[:buildings])
      else
        @battery = Battery.all
      end
    end

    def get_buildings_by_customer
      puts params[:customer_id]
      @buildings = Building.where(customer_id: params[:customer_id])
      puts @buildings.count
      respond_to do |format|
        format.json { render :json => @buildings }
      end
    end 
    def building_search
      if params[:location].present? && params[:customer].strip != ""
        @buildings = Building.where("customer_id = ?", params[:customer])
      else
        @buildings = Building.all
      end
    end
  
    def create
  
      @intervention = Intervention.new

      @intervention.author = params['author']
      @intervention.customer_id = params['intervention']['customer']
      @intervention.building_id = params['intervention']['building_id']
      @intervention.battery_id = params['intervention']['battery_id'] if params['intervention']['column_id'] == ""
      @intervention.column_id = params['intervention']['column_id'] if params['intervention']['elevator_id'] == ""
      @intervention.elevator_id = params['intervention']['elevator_id']
      @intervention.employee_id = params['intervention']['employee_id']
      @intervention.report = params['report_intervention']
    
      @intervention.save!
      
        if params['intervention']['column_id'] == ""
        @intervention.get_interventions_battery
      elsif params['intervention']['elevator_id'] == ""
        @intervention.get_interventions_column
      else 
        @intervention.get_interventions_elevator
      end
    
        redirect_to root_path
    
      end
  
    # GET /interventions
    # GET /interventions.json
    def index
      @intervention.get_a_intervention
      @intervention = intervention.all
    end
  
    # GET /interventions/1
    # GET /interventions/1.json
    def show
    end
  
  
  
    # GET /interventions/1/edit
    def edit
    end
  
    # POST /interventions
    # POST /interventions.json
  
      respond_to do |format|
        if @intervention.save
          format.html { redirect_to @intervention, notice: 'intervention was successfully created.' }
          format.json { render :show, status: :created, location: @intervention }
        else
          format.html { render :new }
          format.json { render json: @intervention.errors, status: :unprocessable_entity }
        end
      end
    
  
    # PATCH/PUT /interventions/1
    # PATCH/PUT /interventions/1.json
    def update
      respond_to do |format|
        if @intervention.update(intervention_params)
          format.html { redirect_to @intervention, notice: 'intervention was successfully updated.' }
          format.json { render :show, status: :ok, location: @intervention }
        else
          format.html { render :edit }
          format.json { render json: @intervention.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /interventions/1
    # DELETE /interventions/1.json
    def destroy
      @intervention.destroy
      respond_to do |format|
        format.html { redirect_to interventions_url, notice: 'intervention was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_intervention
        @intervention = intervention.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def intervention_params
        params.fetch(:intervention, {})
      end 
    end

app/controllers/interventions_controller.rb
require './lib/API/zendesk.rb'
class InterventionsController < ApplicationController
   
	skip_before_action :verify_authenticity_token
  before_action :set_intervention, only: [:show, :edit, :update, :destroy]
   
    def new
      @interventions = Intervention.new
    end

    def get_elevator_by_column
      puts params[:column_id]
        @elevator = Elevator.where("column_id = ?", params[:column_id])
        puts @elevator
        respond_to do |format|
          format.json { render :json => @elevator }
        end
      end 
      def elevator_search
        if params[:location].present? && params[:column].strip != ""
          @elevator = Elevator.where("column_id = ?", params[:column])
        else
          @elevator = Elevator.all
        end
      end
    def get_column_by_battery
      @column = Column.where("battery_id = ?", params[:battery_id])
      puts @column
      respond_to do |format|
        format.json { render :json => @column }
      end
    end 
    def column_search
      if params[:location].present? && params[:battery_id].strip != ""
        @column = Column.where("battery_id = ?", params[:battery_id])
      else
        @column = Column.all
      end
    end

    def get_battery_by_buildings
      @battery = Battery.where(building_id: params[:buildings_id])
      puts @battery
      respond_to do |format|
        format.json { render :json => @battery }
      end
    end 
    def battery_search
      if params[:location].present? && params[:buildings].strip != ""
        @battery = Battery.where("buildings_id = ?", params[:buildings])
      else
        @battery = Battery.all
      end
    end

    def get_buildings_by_customer
      puts params[:customer_id]
      @buildings = Building.where(customer_id: params[:customer_id])
      puts @buildings.count
      respond_to do |format|
        format.json { render :json => @buildings }
      end
    end 
    def building_search
      if params[:location].present? && params[:customer].strip != ""
        @buildings = Building.where("customer_id = ?", params[:customer])
      else
        @buildings = Building.all
      end
    end
  
    def create
  
      @interventions = Intervention.new

      @interventions.author = params['author']
      @interventions.customer_id = params['intervention']['customer']
      @interventions.building_id = params['intervention']['building_id']
      @interventions.battery_id = params['intervention']['battery_id'] if params['intervention']['column_id'] == ""
      @interventions.column_id = params['intervention']['column_id'] if params['intervention']['elevator_id'] == ""
      @interventions.elevator_id = params['intervention']['elevator_id']
      @interventions.employee_id = params['intervention']['employee_id']
      @interventions.rapport = params['rapport']
    
     
    
      #   if params['intervention']['column_id'] == ""
      #   @interventions.get_interventions_battery
      # elsif params['intervention']['elevator_id'] == ""
      #   @interventions.get_interventions_column
      # else
      #   @interventions.get_interventions_elevator
     
      @interventions.save!
      get_intervention(@interventions)
      redirect_to root_path
      end

      def get_intervention(interventions)

        customer_info = interventions.customer.company_name
        building_nb = interventions.building_id
        address_number = interventions.building.address.number_and_street
        address_city = interventions.building.address.city
        battery_nb = interventions.battery_id
        column_nb = interventions.column_id
        elevator_nb = interventions.elevator_id
        employee_name = interventions.employee.first_name
        employee_lastname = interventions.employee.last_name
        report_info = interventions.rapport
    
      zendesk = Zendesk.new
      zendesk.get_an_intervention(
        customer_info, 
        building_nb, 
        address_number, 
        address_city, 
        battery_nb, 
        column_nb,
        elevator_nb,
        employee_name, 
        employee_lastname) 
    end 
  
    # GET /intervention
    # GET /intervention.json
    def index
      @interventions = intervention.all
    end
  
    # GET /intervention/1
    # GET /intervention/1.json
    def show
    end
  
  
  
    # GET /intervention/1/edit
    def edit
    end
  
    # POST /intervention
    # POST /intervention.json
  
      respond_to do |format|
        if @intervention.save
          format.html { redirect_to @intervention, notice: 'intervention was successfully created.' }
          format.json { render :show, status: :created, location: @intervention }
        else
          format.html { render :new }
          format.json { render json: @intervention.errors, status: :unprocessable_entity }
        end
      end
    
  
    # PATCH/PUT /intervention/1
    # PATCH/PUT /intervention/1.json
    def update
      respond_to do |format|
        if @intervention.update(intervention_params)
          format.html { redirect_to @intervention, notice: 'intervention was successfully updated.' }
          format.json { render :show, status: :ok, location: @intervention }
        else
          format.html { render :edit }
          format.json { render json: @intervention.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /intervention/1
    # DELETE /intervention/1.json
    def destroy
      @intervention.destroy
      respond_to do |format|
        format.html { redirect_to intervention_url, notice: 'intervention was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_intervention
        @intervention = intervention.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def intervention_params
        params.fetch(:intervention, {})
      end 
    
  end


app/helpers/intervention_helper.rb
module InterventionHelper
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_buildings_list.html.erb
<% buildings.each do |buildings| %>
  <%= buildings.id %>
  <%= buildings.title %>
  <hr />
<% end %>

app/views/interventions/_column_list.html.erb
<% column.each do |column| %>
  <%= column.id %>
  <%= column.information %>
  <hr />
<% end %>

app/views/interventions/_elevator_list.html.erb
<% elevator.each do |elevator| %>
  <%= elevator.id %>
  <%= elevator.information %>
  <hr />
<% end %>

app/views/interventions/_form.html.erb
<%= form_with(model: intervention, local: true) do |form| %>
  <% if intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interventions/battery_search.js.erb
$('#battery_listing').html('<%= j render partial: "battery_list", locals: {battery: @battery} %>')

app/views/interventions/buildings_search.html.erb
<div class="row no-gutters wow slideInUp" data-wow-duration="1s">
  <div class="col-md-12 home-form">
    <%= form_tag(buildings_search_path, method: "get", class: "form-inline", remote: true) do %>
    <%= select_tag "customer", options_from_collection_for_select(Customer.all, "id", "header"), prompt: "Customer", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
    <%= select_tag "buildings_type", options_from_collection_for_select(Buildings.all, "id", "buildings_type"), prompt: "Buildings Type", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
    <%= select_tag "course", options_from_collection_for_select(Buildings.all, "id", "title"), prompt: "Buildings", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
    <%= submit_tag("Search", class: "btn btn-primary") %>
<% end %>
  </div>
</div>

<div class="row" id="buildings_listing">
  <%= render partial: "buildings_list", locals: {buildings: @buildings} %>
</div>

app/views/interventions/buildings_search.js.erb
$('#buildings_listing').html('<%= j render partial: "buildings_list", locals: {buildings: @buildings} %>')

app/views/interventions/column_search.html.erb
<div class="row no-gutters wow slideInUp" data-wow-duration="1s">
  <div class="col-md-12 home-form">
    <%= form_tag(column_search_path, method: "get", class: "form-inline", remote: true) do %>
    <%= select_tag "battery", options_from_collection_for_select(Battery.all, "id", "header"), prompt: "Battery", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
    <%= select_tag "column_type", options_from_collection_for_select(Column.all, "id", "column_type"), prompt: "Column Type", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
    <%= select_tag "course", options_from_collection_for_select(Column.all, "id", "title"), prompt: "Column", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
    <%= submit_tag("Search", class: "btn btn-primary") %>
<% end %>
  </div>
</div>

<div class="row" id="column_listing">
  <%= render partial: "column_list", locals: {column: @column} %>
</div>

app/views/interventions/column_search.js.erb
$('#column_listing').html('<%= j render partial: "column_list", locals: {column: @column} %>')

app/views/interventions/elevator_search.html.erb
<div class="row no-gutters wow slideInUp" data-wow-duration="1s">
  <div class="col-md-12 home-form">
    <%= form_tag(elevator_search_path, method: "get", class: "form-inline", remote: true) do %>
    <%= select_tag "column", options_from_collection_for_select(Column.all, "id", "header"), prompt: "Column", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
    <%= select_tag "elevator_type", options_from_collection_for_select(Elevator.all, "id", "elevator_type"), prompt: "Elevator Type", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
    <%= select_tag "course", options_from_collection_for_select(Elevator.all, "id", "title"), prompt: "Elevator", class: "custom-select mb-0 mr-sm-0 mb-sm-0" %>
    <%= submit_tag("Search", class: "btn btn-primary") %>
<% end %>
  </div>
</div>

<div class="row" id="elevator_listing">
  <%= render partial: "elevator_list", locals: {elevator: @elevator} %>
</div>

app/views/interventions/elevator_search.js.erb
$('#elevator_listing').html('<%= j render partial: "elevator_list", locals: {elevator: @elevator} %>')

app/views/interventions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interventions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interventions.each do |intervention| %>
      <tr>
        <td><%= link_to 'Show', intervention %></td>
        <td><%= link_to 'Edit', edit_intervention_path(intervention) %></td>
        <td><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Intervention', new_intervention_path %>

app/views/interventions/new.html.erb





                    <section class="page-header quoteHeaderColor">
                    <div class="container">
    
                        <h1 class= "titleStyle">Intervention Form</h1>
    
                        <!-- breadcrumbs -->
                        <ol class="breadcrumb">
                            <li><a href="/" style="color:white">Home</a></li>
                            <li class="active">Rocket</li>
                        </ol><!-- /breadcrumbs -->
    
                    </div>
            </section>
                <!-- /PAGE HEADER -->


            <%= form_for @interventions do |f| %>

                <!-- form -->
                 <!-- client name -->
                 <section class= "formStyle" id= "toPrintQuote">

                    <div class= "chooseType">
                    <label for="customer_id" class="labelStyle">Author</label>
                    <input name = "author" style = "display: none;" type= "string" id= "author" readonly value="<%="#{current_user.employee.id}"%>">
                    <input name = "author_show" type= "string" readonly value="<%=  "#{current_user.employee.name}"%>"> 

                    <div class= "chooseType" id="customer">
                        <label for="customer_id" class="labelStyle">Client Name</label>
                        <%= f.collection_select(:customer, Customer.all, :id, :company_name, {:prompt=>'Select Customer'}, {:class=>'customer_id'}) %>
                    </div>
                    <!-- /client name -->
                    <!-- client building -->
                        <div class= "chooseType" style = "display: none;" id="buildings_select">
                            <label class= "labelStyle">Client's Building :</label>
                            <%= f.collection_select(:building_id, Building.all, :id, :building_info, {:prompt=>'Select Building'}, {:class=>'building_id'}) %>
                        </div>      
                    <!-- client battery -->
                     <div class= "chooseType"  style = "display: none;" id="batteries_select">
                            <label class= "labelStyle">Client's Batteries :</label>
                            <%= f.collection_select(:battery_id, Battery.all, :id, :operation_certificate, {:prompt=>'Select Battery'}, {:class=>'battery_id'}) %>
                        </div>  
                    <!-- /client battery --> 
                    <!-- client column -->
                     <div class= "chooseType" style = "display: none;" id="columns_select">
                            <label class= "labelStyle">Client's Column :</label>
                            <%= f.collection_select(:column_id, Column.all, :id, :id, {:prompt=>'Select Column'}, {:class=>'column_id'}) %>
                        </div> 
                    <!-- /client column -->
                    <!-- client elevator -->
                       <div class= "chooseType"  style = "display: none;" id="elevators_select">
                            <label class= "labelStyle">Client's Elevator :</label>
                            <%= f.collection_select(:elevator_id, Elevator.all, :id, :id, {:prompt=>'Select Elevator'}, {:class=>'elevator_id'}) %>
                        </div> 
                    <!-- /client elevator -->
                    <!-- client employee -->
                    <div class= "chooseType">
                            <label class= "labelStyle">Client's Employee :</label>
                            <%= f.collection_select(:employee_id, Employee.all, :id, :first_name, {:prompt=>'Select Employee'}, {:class=>'employe_id'}) %>
                        </div>
                    <br>                  
                    
                    
                   
                   
                     <%= f.submit %>

                </section>
                <!-- /form -->
            <% end %>

            
    
            

<!-- JAVASCRIPT FILES -->



<!-- REVOLUTION SLIDER -->
<%# <script src="/assets/plugins/slider.revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="/assets/plugins/slider.revolution/js/jquery.themepunch.revolution.min.js"></script>
<script src="/assets/js/view/demo.revolution_slider.js"></script> %>

<!-- PAGELEVEL SCRIPTS -->
<%# <script src="/assets/js/contact.js"></script> %>
  

app/views/interventions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_intervention_path(@intervention) %> |
<%= link_to 'Back', interventions_path %>